Vagrant.configure("2") do |config|
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true

    ### Worker ### 
    config.vm.define "web01" do |web01|
        web01.vm.box = "ubuntu/xenial64"
        web01.vm.hostname ="web01"
        web01.vm.network  "private_network", ip: "192.168.33.12"
        web01.vm.provider "virtualbox" do |vb|
            vb.memory = 2048
	    end   
        web01.vm.synced_folder  "../vprofile-code", "/vprofile-data"
    end


     ### Control Plane or Manager are same ###
    config.vm.define "app01" do |app01|
        app01.vm.box = "geerlingguy/centos7"
        app01.vm.hostname ="app01"
        app01.vm.provider "virtualbox" do |vb|
            vb.memory = 2048
            vb.cpus = 2
	    end
        app01.vm.network "private_network", ip:"192.168.33.13", :netmask => "255.255.255.0"
        app01.vm.synced_folder  "../vprofile-code", "/vprofile-data"
        app01.vm.provision "shell", inline: "shell", inline: <<-SHELL
        sudo nmcli con add con-name enp0s8 ifname enp0s8 type ethernet ip4 192.168.33.13/24
        sudo nmcli con up  enp0s8
        # yum update -y
        yum install wget epel-release -y
    SHELL
    end
        
    
        ## Worker 1 ##
    config.vm.define "rmq01" do |rmq01|
        rmq01.vm.box = "geerlingguy/centos7"
        rmq01.vm.hostname ="rmq01"
        rmq01.vm.network "private_network", ip:"192.168.33.14", :netmask => "255.255.255.0"
        rmq01.vm.provider "virtualbox" do |vb|
            vb.memory = 2048
	    end
        rmq01.vm.synced_folder  "../vprofile-code", "/vprofile-data"
        rmq01.vm.provision "shell", inline: <<-SHELL
        sudo nmcli con add con-name enp0s8 ifname enp0s8 type ethernet ip4 192.168.33.14/24
        sudo nmcli con up  enp0s8
        yum install wget epel-release -y
        SHELL
        
       
    end 
    
    ## Worker 2 ##
    config.vm.define "mc01" do |mc01|
        mc01.vm.box = "geerlingguy/centos7"
        mc01.vm.hostname ="mc01"
        mc01.vm.network "private_network", ip:"192.168.33.15"
        mc01.vm.provider "virtualbox" do |vb|
            vb.memory = 2048
	    end
        mc01.vm.synced_folder  "../vprofile-code", "/vprofile-data"
        mc01.vm.provision "shell", inline: <<-SHELL
        sudo nmcli con add con-name enp0s8 ifname enp0s8 type ethernet ip4 192.168.33.15/24
        sudo nmcli con up  enp0s8
        yum install wget epel-release -y
        SHELL
        
    end

    # Worker node. 
    config.vm.define "mc02" do |mc02|
        mc02.vm.box = "geerlingguy/centos7"
        mc02.vm.hostname ="mc01"
        mc02.vm.network "private_network", ip:"192.168.33.16"
        mc02.vm.provider "virtualbox" do |vb|
            vb.memory = 2048
	    end
        mc02.vm.synced_folder  "../vprofile-code", "/vprofile-data"
        mc02.vm.provision "shell", inline: <<-SHELL
        sudo nmcli con add con-name enp0s8 ifname enp0s8 type ethernet ip4 192.168.33.16/24
        sudo nmcli con up  enp0s8
        yum install wget epel-release -y
        SHELL
        
    end
    
end    
   

