# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  # config.vm.provision "shell", path: "bootstrap.sh"
  NodeCount = 5 
  # Kubernetes Nodes + Bootstrap node. 

  (1..NodeCount).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.box = "geerlingguy/centos7"
      node.vm.hostname = "node#{i}.example.com"
      node.vm.network "private_network", ip: "172.16.16.10#{i}"
      node.vm.provision "shell", inline: <<-SHELL
      # Enable SSH.
      echo "[TASK 1] Enable ssh password authentication"
      sed -i.bak 's/^PasswordAuthentication .*/PasswordAuthentication yes/' /etc/ssh/sshd_config
      echo -e '\nPermitRootLogin yes' >> /etc/ssh/sshd_config
      systemctl reload-or-restart sshd

      # Set Root password
      echo "[TASK 2] Set root password"
      echo -e "password" | passwd --stdin root >/dev/null 2>&1

      # Set network connection. 
      nmcli con add con-name enp0s8 ifname enp0s8 type ethernet ip4 172.16.16.10#{i}/24
      nmcli con up  enp0s8
      SHELL
      node.vm.provider "virtualbox" do |v|
        v.name = "node#{i}"
        v.memory = 2048
        v.cpus = 2
      end
    end
  end
end
   

